# Generated by Django 6.0.1 on 2026-02-15 04:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text="e.g., 'Fall 2024', 'Spring 2025'", max_length=100)),
                ('academic_year', models.CharField(db_index=True, help_text="e.g., '2024-2025'", max_length=10)),
                ('semester', models.CharField(choices=[('first', 'First Semester'), ('second', 'Second Semester'), ('summer', 'Summer Term'), ('trimester', 'Trimester')], max_length=20)),
                ('evaluation_type', models.CharField(choices=[('midterm', 'Midterm Evaluation'), ('final', 'Final Evaluation'), ('annual', 'Annual Review'), ('special', 'Special Evaluation')], default='final', max_length=20)),
                ('start_date', models.DateTimeField(db_index=True)),
                ('end_date', models.DateTimeField(db_index=True)),
                ('extension_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('closed', 'Closed'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('allow_late_submissions', models.BooleanField(default=False)),
                ('require_comments', models.BooleanField(default=False)),
                ('minimum_responses_required', models.PositiveIntegerField(default=0, help_text='Minimum responses before report generation')),
                ('results_visible_to_teachers', models.BooleanField(default=False)),
                ('results_visible_to_students', models.BooleanField(default=False)),
                ('results_visibility_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evaluation Period',
                'verbose_name_plural': 'Evaluation Periods',
                'db_table': 'evaluation_periods',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('student_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('middle_name', models.CharField(blank=True, default='', max_length=150)),
                ('contact_number', models.CharField(blank=True, default='', max_length=20)),
                ('year_level', models.PositiveIntegerField(blank=True, choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year'), (4, 'Fourth Year')], null=True)),
                ('program', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('tl', 'Tagalog')], default='en', max_length=10)),
                ('receive_notifications', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluator_type', models.CharField(choices=[('student', 'Student Evaluation'), ('peer', 'Peer Evaluation'), ('self', 'Self Evaluation'), ('admin', 'Administrative Review'), ('supervisor', 'Supervisor Review')], db_index=True, default='student', max_length=20)),
                ('evaluator_name', models.CharField(blank=True, default='', help_text='Name for non-student evaluators', max_length=255)),
                ('evaluator_email', models.EmailField(blank=True, default='', help_text='Email for non-student evaluators', max_length=254)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('progress_percentage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('device_id', models.CharField(blank=True, default='', max_length=100)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('show_respondent_in_report', models.BooleanField(default=False)),
                ('overall_rating', models.DecimalField(blank=True, db_index=True, decimal_places=2, help_text='Calculated overall rating (1-5)', max_digits=3, null=True)),
                ('summary_comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, default='')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to=settings.AUTH_USER_MODEL)),
                ('evaluation_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='core.evaluationperiod')),
            ],
            options={
                'verbose_name': 'Evaluation',
                'verbose_name_plural': 'Evaluations',
                'db_table': 'evaluations',
            },
        ),
        migrations.CreateModel(
            name='EvaluationAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('question_number', models.IntegerField(default=1)),
                ('rating', models.IntegerField()),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_answers', to='core.evaluation')),
            ],
            options={
                'verbose_name': 'Evaluation Answer (Legacy)',
                'db_table': 'evaluation_answers',
            },
        ),
        migrations.CreateModel(
            name='EvaluationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text="e.g., 'Teaching Methodology'", max_length=100)),
                ('code', models.CharField(db_index=True, help_text='Short code for identification', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Weight factor for category scoring', max_digits=5)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Order of display in evaluation form')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_required', models.BooleanField(default=True, help_text='Category must have responses')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluation_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.evaluationperiod')),
            ],
            options={
                'verbose_name': 'Evaluation Category',
                'verbose_name_plural': 'Evaluation Categories',
                'db_table': 'evaluation_categories',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField(default=1, help_text='Question number for ordering')),
                ('question_text', models.TextField(help_text='The actual question to be displayed')),
                ('question_text_localized', models.JSONField(blank=True, default=dict, help_text='Localized versions of question text')),
                ('help_text', models.TextField(blank=True, default='', help_text='Additional guidance for respondents')),
                ('question_type', models.CharField(choices=[('rating', 'Rating Scale (1-5)'), ('rating_10', 'Rating Scale (1-10)'), ('boolean', 'Yes/No'), ('text', 'Short Text'), ('textarea', 'Long Text'), ('multiple_choice', 'Multiple Choice')], default='rating', max_length=20)),
                ('rating_scale', models.CharField(choices=[('1-5', '1-5 Scale'), ('1-10', '1-10 Scale'), ('1-7', '1-7 Scale')], default='1-5', max_length=10)),
                ('min_rating', models.PositiveIntegerField(default=1)),
                ('max_rating', models.PositiveIntegerField(default=5)),
                ('is_required', models.BooleanField(db_index=True, default=True)),
                ('allow_na', models.BooleanField(default=False, help_text='Allow Not Applicable option')),
                ('max_length', models.PositiveIntegerField(blank=True, help_text='Max character length for text responses', null=True)),
                ('choices', models.JSONField(blank=True, help_text='Options for multiple choice questions', null=True)),
                ('positive_weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Weight for positive responses', max_digits=5)),
                ('reverse_scored', models.BooleanField(default=False, help_text='Reverse scoring (high score = negative)')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.evaluationcategory')),
            ],
            options={
                'verbose_name': 'Evaluation Question',
                'verbose_name_plural': 'Evaluation Questions',
                'db_table': 'evaluation_questions',
                'ordering': ['category', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(blank=True, db_index=True, decimal_places=2, help_text='Numeric rating value', max_digits=5, null=True)),
                ('text_response', models.TextField(blank=True, default='')),
                ('boolean_response', models.BooleanField(blank=True, null=True)),
                ('choice_response', models.CharField(blank=True, default='', max_length=100)),
                ('is_na', models.BooleanField(default=False, help_text='Marked as Not Applicable')),
                ('na_reason', models.CharField(blank=True, default='', max_length=255)),
                ('weighted_score', models.DecimalField(blank=True, decimal_places=2, help_text='Pre-computed weighted score', max_digits=5, null=True)),
                ('responded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.evaluation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='core.evaluationquestion')),
            ],
            options={
                'verbose_name': 'Evaluation Response',
                'verbose_name_plural': 'Evaluation Responses',
                'db_table': 'evaluation_responses',
            },
        ),
        migrations.CreateModel(
            name='Evaluator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(blank=True, help_text='Link to Django auth User model', null=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('employee_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('department', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('admin', 'System Administrator'), ('department_head', 'Department Head'), ('evaluations_manager', 'Evaluations Manager'), ('report_viewer', 'Report Viewer')], default='report_viewer', max_length=30)),
                ('permissions', models.JSONField(blank=True, default=dict, help_text='Granular permissions configuration')),
                ('department_access', models.CharField(blank=True, default='', help_text='Restrict access to specific departments', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_evaluators', to='core.evaluator')),
            ],
            options={
                'verbose_name': 'Evaluator',
                'verbose_name_plural': 'Evaluators',
                'db_table': 'evaluators',
            },
        ),
        migrations.AddField(
            model_name='evaluationperiod',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_periods', to='core.evaluator'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='core.evaluator'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, db_index=True, default='', max_length=20, unique=True, verbose_name='employee identification number')),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, default='', max_length=150)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('alternate_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_number', models.CharField(blank=True, default='', max_length=20)),
                ('subject', models.CharField(db_index=True, max_length=255)),
                ('department', models.CharField(db_index=True, max_length=255)),
                ('position', models.CharField(choices=[('Instructor', 'Instructor'), ('Assistant Professor', 'Assistant Professor'), ('Associate Professor', 'Associate Professor'), ('Professor', 'Professor'), ('Department Head', 'Department Head'), ('Dean', 'Dean')], default='Faculty', max_length=100)),
                ('highest_degree', models.CharField(blank=True, choices=[('', 'Not Specified'), ('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Doctorate', 'Doctorate'), ('Post-Doctorate', 'Post-Doctorate')], default='', max_length=50)),
                ('specializations', models.JSONField(blank=True, default=list, help_text='List of subject specializations')),
                ('employment_status', models.CharField(choices=[('full-time', 'Full-Time'), ('part-time', 'Part-Time'), ('contractual', 'Contractual'), ('adjunct', 'Adjunct'), ('on-leave', 'On Leave')], default='full-time', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'db_table': 'teachers',
                'indexes': [models.Index(fields=['email'], name='idx_teacher_email'), models.Index(fields=['department'], name='idx_teacher_dept'), models.Index(fields=['subject'], name='idx_teacher_subject'), models.Index(fields=['is_active'], name='idx_teacher_active'), models.Index(fields=['full_name'], name='idx_teacher_name'), models.Index(fields=['created_at'], name='idx_teacher_created')],
            },
        ),
        migrations.CreateModel(
            name='EvaluationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(db_index=True, help_text='Unique report identifier', max_length=50, unique=True)),
                ('report_type', models.CharField(choices=[('teacher_summary', 'Teacher Summary Report'), ('department_summary', 'Department Summary Report'), ('detailed_analysis', 'Detailed Analysis Report'), ('comparative_analysis', 'Comparative Analysis Report'), ('trend_analysis', 'Trend Analysis Report'), ('student_feedback', 'Student Feedback Summary'), ('compliance_report', 'Compliance Report')], db_index=True, max_length=30)),
                ('report_format', models.CharField(choices=[('pdf', 'PDF Document'), ('excel', 'Excel Spreadsheet'), ('csv', 'CSV Data'), ('json', 'JSON Data')], default='pdf', max_length=10)),
                ('department', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('data_snapshot', models.JSONField(default=dict, help_text='Complete report data snapshot')),
                ('generated_html', models.TextField(blank=True, default='', help_text='Pre-rendered HTML for web display')),
                ('summary_statistics', models.JSONField(blank=True, default=dict, help_text='Key statistics (mean, median, std dev, etc.)')),
                ('file_path', models.CharField(blank=True, default='', max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('generation_params', models.JSONField(default=dict, help_text='Parameters used to generate this report')),
                ('is_public', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('evaluation_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='core.evaluationperiod')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to='core.evaluator')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.teacher')),
            ],
            options={
                'verbose_name': 'Evaluation Report',
                'verbose_name_plural': 'Evaluation Reports',
                'db_table': 'evaluation_reports',
            },
        ),
        migrations.AddField(
            model_name='evaluation',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='core.teacher'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['email'], name='idx_student_email'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_id'], name='idx_student_id'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['is_active'], name='idx_student_active'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['created_at'], name='idx_student_created'),
        ),
        migrations.AddIndex(
            model_name='evaluationanswer',
            index=models.Index(fields=['evaluation'], name='idx_answer_evaluation'),
        ),
        migrations.AddIndex(
            model_name='evaluationcategory',
            index=models.Index(fields=['code'], name='idx_category_code'),
        ),
        migrations.AddIndex(
            model_name='evaluationcategory',
            index=models.Index(fields=['is_active'], name='idx_category_active'),
        ),
        migrations.AddIndex(
            model_name='evaluationcategory',
            index=models.Index(fields=['display_order'], name='idx_category_order'),
        ),
        migrations.AddIndex(
            model_name='evaluationquestion',
            index=models.Index(fields=['category'], name='idx_question_category'),
        ),
        migrations.AddIndex(
            model_name='evaluationquestion',
            index=models.Index(fields=['is_active'], name='idx_question_active'),
        ),
        migrations.AddIndex(
            model_name='evaluationquestion',
            index=models.Index(fields=['question_number'], name='idx_question_number'),
        ),
        migrations.AddIndex(
            model_name='evaluationquestion',
            index=models.Index(fields=['display_order'], name='idx_question_order'),
        ),
        migrations.AddConstraint(
            model_name='evaluationquestion',
            constraint=models.UniqueConstraint(fields=('category', 'question_number'), name='uq_category_question_number'),
        ),
        migrations.AddIndex(
            model_name='evaluationresponse',
            index=models.Index(fields=['evaluation'], name='idx_response_eval'),
        ),
        migrations.AddIndex(
            model_name='evaluationresponse',
            index=models.Index(fields=['question'], name='idx_response_question'),
        ),
        migrations.AddIndex(
            model_name='evaluationresponse',
            index=models.Index(fields=['rating'], name='idx_response_rating'),
        ),
        migrations.AddIndex(
            model_name='evaluationresponse',
            index=models.Index(fields=['is_na'], name='idx_response_na'),
        ),
        migrations.AddIndex(
            model_name='evaluationresponse',
            index=models.Index(fields=['evaluation', 'question'], name='idx_response_eval_question'),
        ),
        migrations.AddConstraint(
            model_name='evaluationresponse',
            constraint=models.UniqueConstraint(fields=('evaluation', 'question'), name='uq_evaluation_question_response'),
        ),
        migrations.AddConstraint(
            model_name='evaluationresponse',
            constraint=models.CheckConstraint(condition=models.Q(('rating__isnull', True), ('rating__gte', 0), _connector='OR'), name='check_rating_non_negative'),
        ),
        migrations.AddIndex(
            model_name='evaluator',
            index=models.Index(fields=['email'], name='idx_evaluator_email'),
        ),
        migrations.AddIndex(
            model_name='evaluator',
            index=models.Index(fields=['role'], name='idx_evaluator_role'),
        ),
        migrations.AddIndex(
            model_name='evaluator',
            index=models.Index(fields=['department'], name='idx_evaluator_dept'),
        ),
        migrations.AddIndex(
            model_name='evaluator',
            index=models.Index(fields=['is_active'], name='idx_evaluator_active'),
        ),
        migrations.AddIndex(
            model_name='evaluationperiod',
            index=models.Index(fields=['name'], name='idx_period_name'),
        ),
        migrations.AddIndex(
            model_name='evaluationperiod',
            index=models.Index(fields=['academic_year'], name='idx_period_year'),
        ),
        migrations.AddIndex(
            model_name='evaluationperiod',
            index=models.Index(fields=['status'], name='idx_period_status'),
        ),
        migrations.AddIndex(
            model_name='evaluationperiod',
            index=models.Index(fields=['start_date', 'end_date'], name='idx_period_dates'),
        ),
        migrations.AddIndex(
            model_name='evaluationperiod',
            index=models.Index(fields=['is_active'], name='idx_period_active'),
        ),
        migrations.AddIndex(
            model_name='evaluationreport',
            index=models.Index(fields=['report_id'], name='idx_report_id'),
        ),
        migrations.AddIndex(
            model_name='evaluationreport',
            index=models.Index(fields=['report_type'], name='idx_report_type'),
        ),
        migrations.AddIndex(
            model_name='evaluationreport',
            index=models.Index(fields=['evaluation_period'], name='idx_report_period'),
        ),
        migrations.AddIndex(
            model_name='evaluationreport',
            index=models.Index(fields=['teacher'], name='idx_report_teacher'),
        ),
        migrations.AddIndex(
            model_name='evaluationreport',
            index=models.Index(fields=['created_at'], name='idx_report_created'),
        ),
        migrations.AddConstraint(
            model_name='evaluationreport',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('teacher__isnull', False), ('department__gt', ''), _connector='OR')), name='check_report_scope'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['evaluation_period'], name='idx_eval_period'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['teacher'], name='idx_eval_teacher'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['evaluator_type'], name='idx_eval_type'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['status'], name='idx_eval_status'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['submitted_at'], name='idx_eval_submitted'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['overall_rating'], name='idx_eval_rating'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['created_at'], name='idx_eval_created'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['student'], name='idx_eval_student'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['evaluator'], name='idx_eval_evaluator'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['evaluation_period', 'teacher'], name='idx_eval_period_teacher'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['evaluation_period', 'status'], name='idx_eval_period_status'),
        ),
    ]
