# Generated by Django 6.0.1 on 2026-02-17 03:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationanswer',
            name='answered_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this answer was submitted'),
        ),
        migrations.AddField(
            model_name='evaluationanswer',
            name='evaluation_comments',
            field=models.TextField(blank=True, default='', help_text='General comments from the evaluation'),
        ),
        migrations.AddField(
            model_name='evaluationanswer',
            name='overall_score',
            field=models.IntegerField(blank=True, help_text='Overall evaluation rating (1-5)', null=True),
        ),
        migrations.AddField(
            model_name='evaluationanswer',
            name='student_email',
            field=models.EmailField(blank=True, default='', help_text='Email of student who submitted this answer', max_length=254),
        ),
        migrations.AddField(
            model_name='evaluationanswer',
            name='student_id',
            field=models.CharField(blank=True, default='', help_text='Student ID from Firebase/system', max_length=100),
        ),
        migrations.AddField(
            model_name='evaluationanswer',
            name='student_name',
            field=models.CharField(blank=True, default='', help_text='Full name of student who submitted this answer', max_length=255),
        ),
        migrations.AddField(
            model_name='evaluationanswer',
            name='teacher_department',
            field=models.CharField(blank=True, default='', help_text='Department of this teacher', max_length=255),
        ),
        migrations.AddField(
            model_name='evaluationanswer',
            name='teacher_name',
            field=models.CharField(blank=True, default='', help_text='Full name of teacher being evaluated', max_length=255),
        ),
        migrations.AddField(
            model_name='evaluationanswer',
            name='teacher_subject',
            field=models.CharField(blank=True, default='', help_text='Subject taught by this teacher', max_length=255),
        ),
        migrations.AlterField(
            model_name='evaluationanswer',
            name='question',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='evaluationanswer',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='evaluationanswer',
            index=models.Index(fields=['student_email'], name='idx_answer_student_email'),
        ),
        migrations.AddIndex(
            model_name='evaluationanswer',
            index=models.Index(fields=['teacher_name'], name='idx_answer_teacher_name'),
        ),
        migrations.AddIndex(
            model_name='evaluationanswer',
            index=models.Index(fields=['answered_at'], name='idx_answer_answered_at'),
        ),
    ]
