# Generated by Django 6.0.1 on 2026-03-05 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_evaluationanswer_answered_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluationperiod',
            options={},
        ),
        migrations.AlterModelOptions(
            name='evaluationreport',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='evaluationreport',
            name='check_report_scope',
        ),
        migrations.RemoveIndex(
            model_name='evaluationperiod',
            name='idx_period_name',
        ),
        migrations.RemoveIndex(
            model_name='evaluationperiod',
            name='idx_period_year',
        ),
        migrations.RemoveIndex(
            model_name='evaluationperiod',
            name='idx_period_status',
        ),
        migrations.RemoveIndex(
            model_name='evaluationperiod',
            name='idx_period_dates',
        ),
        migrations.RemoveIndex(
            model_name='evaluationperiod',
            name='idx_period_active',
        ),
        migrations.RemoveIndex(
            model_name='evaluationreport',
            name='idx_report_id',
        ),
        migrations.RemoveIndex(
            model_name='evaluationreport',
            name='idx_report_type',
        ),
        migrations.RemoveIndex(
            model_name='evaluationreport',
            name='idx_report_period',
        ),
        migrations.RemoveIndex(
            model_name='evaluationreport',
            name='idx_report_teacher',
        ),
        migrations.RemoveIndex(
            model_name='evaluationreport',
            name='idx_report_created',
        ),
        migrations.AlterModelTable(
            name='evaluationperiod',
            table=None,
        ),
        migrations.AlterModelTable(
            name='evaluationreport',
            table=None,
        ),
    ]
